### ISSUE TITLE
Demo Ready Tracking Tasks

### ISSUE THREAD

**Issue by nerdalert** [redhat-et/apex#105]
These are the tasks required to hit the mvp demo in mid November:

- [x] IPAM persistence between restarts (technically not really required for the demo though but being able to support controller restart persistence is critical). #97 #63 
- [x] Hybrid mesh discovery - Users need to be able to peer to local nodes and bounce to hub #98 #102
- [x] Automated stress test - to ensure we can scale to x number of nodes. #103. 
- [x] Automate the demo deployment at large scale 100+ nodes and multi-cloud. #103 
- [x] :warning: Provisioning - user redirect to auth page from the client `apex init` (or some command) and then a join is triggered #104
- [x] Key generation by the agent  #109
- [x] UX? ¯\_(ツ)_/¯ 
- [x] Pricing in a SaaS model (ballpark of the EC2 cost per stack) (Slide in Anil's deck)
- [x] Developer setup with the stack documented #107 
- [x] :warning: A user onboarding in the demo will need to land in a hub-zone enabled zone. This rules out the default zone which is mesh with no bouncer. This would mean the org would need to be associated to a hub enabled zone or the agent would default to mesh only.
- [x] : Node setup script for users which will install wireguard and pull down the binary - Apex Init (Anil) 
- [x] Agent Panic when controller goes away #94 
- [x] Host on K8s
- [ ] Configure Keycloak with a "production" auth

*Stretch goals*:
- [ ] (Stretch) DNS #30 
Please add what tasks are missing! <3
